plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.muhammedrizaguler.bitirmeprojesi'
    compileSdk 35

    defaultConfig {
        applicationId "com.muhammedrizaguler.bitirmeprojesi"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // ✅ Media3 (ExoPlayer RTSP) – güncel sürüm (2025 itibarıyla)
    implementation 'androidx.media3:media3-exoplayer:1.5.1'
    implementation 'androidx.media3:media3-exoplayer-rtsp:1.5.1'
    implementation 'androidx.media3:media3-ui:1.5.1'
}
